### ISSUE TITLE
PID 01A6: Odometer doesn't respond to ECU 7E0

### ISSUE THREAD

**Issue by electricsidecar-dev** [OBDb/BMW-X3#4]
This works however:

```
ATSH7DF	OK
01A6	7E80641A6000B477D
```

As of Sidecar v1.19, it will always attempt to send service 01 commands to the -08 offset ECU from the response CAN-ID, which is 7E8. Sidecar will need to add the ability to send service 01 commands to different ECUs in order to fix this bug.

**Comment by jverkoey** [comment]
This is confirmed fixed in v1.20.
